name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch Submodules
      run: |
        git submodule update --init --depth=1
    - name: Setup Emscripten
      run: |
        ./emsdk/emsdk install latest
        ./emsdk/emsdk activate latest
    - name: Make
      run: |
        source ./emsdk/emsdk_env.sh
        make
